#!/usr/bin/env node
/**
 * Pulls published content (draft = false) from Supabase into
 * src/content/generated/*.ts before `vite-react-ssg build` runs, so the
 * public pages keep shipping complete, real content in their prerendered
 * HTML -- no runtime fetch, no loading state, no regression against the
 * site's "crawlable without JavaScript" design. Generated as .ts rather than
 * .json so the output is type-checked like everything else and can carry a
 * header comment (JSON has no comment syntax).
 *
 * The generated files are committed to git, not gitignored: if Supabase is
 * briefly unreachable, or a contributor has no service-role key configured
 * locally, this script logs a warning and leaves the last-committed
 * snapshot in place rather than failing the entire site's build over a
 * content fetch hiccup.
 *
 * Uses SUPABASE_SERVICE_ROLE_KEY (plain, not VITE_-prefixed -- never
 * imported from src/, so it can never end up in the client bundle) because
 * it needs to read draft rows too (to filter them out itself) and content
 * tables have no public/anon SELECT policy.
 *
 * Run automatically as part of `npm run build`. Safe to run locally too:
 * `node scripts/fetch-content.mjs`.
 */
import { createClient } from '@supabase/supabase-js'
import { mkdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

// eslint-disable-next-line no-underscore-dangle -- standard ESM __dirname shim
const __dirname = path.dirname(fileURLToPath(import.meta.url))
const OUT_DIR = path.resolve(__dirname, '../src/content/generated')

const url = process.env.VITE_SUPABASE_URL
const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY

if (!url || !serviceKey) {
  console.warn(
    '[fetch-content] VITE_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY not set -- ' +
      'skipping fetch, build will use the last-committed content snapshot.',
  )
  process.exit(0)
}

const supabase = createClient(url, serviceKey)

const header = (table) =>
  `// AUTO-GENERATED by scripts/fetch-content.mjs from Supabase's "${table}" table.\n` +
  `// Do not hand-edit -- edit the content in the admin panel instead, then\n` +
  `// re-run this script (or just push; it also runs before every build).\n\n`

async function fetchTable(table, mapRow) {
  const { data, error } = await supabase
    .from(table)
    .select('*')
    .eq('draft', false)
    .order('sort_order', { ascending: true })

  if (error) {
    console.warn(
      `[fetch-content] Failed to fetch "${table}" (${error.message}) -- ` +
        'keeping the last-committed snapshot for this file.',
    )
    return null
  }

  return data.map(mapRow)
}

function writeModule(filename, table, exportName, data) {
  const outPath = path.join(OUT_DIR, filename)
  const body = `export const ${exportName} = ${JSON.stringify(data, null, 2)}\n`
  writeFileSync(outPath, header(table) + body)
  console.log(
    `[fetch-content] Wrote ${data.length} row(s) to ${path.relative(process.cwd(), outPath)}`,
  )
}

mkdirSync(OUT_DIR, { recursive: true })

const journal = await fetchTable('journal_entries', (row) => ({
  slug: row.slug,
  format: row.format,
  title: row.title,
  excerpt: row.excerpt,
  imageLabel: row.image_label ?? '',
  ...(row.image_url ? { image: row.image_url } : {}),
  ...(row.image_alt ? { imageAlt: row.image_alt } : {}),
  // The site's own JournalEntry.draft field is a content-level display flag
  // (the "illustrative" badge) -- distinct from this table's `draft` column,
  // which is the publish gate this fetch already filtered on above.
  draft: row.illustrative,
}))
if (journal) writeModule('journal.ts', 'journal_entries', 'entries', journal)

const events = await fetchTable('cercle_events', (row) => ({
  slug: row.slug,
  name: row.name,
  status: row.status,
  ...(row.kicker ? { kicker: row.kicker } : {}),
  blurb: row.blurb,
  ...(row.description ? { description: row.description } : {}),
  ...(row.meta ? { meta: row.meta } : {}),
  imageLabel: row.image_label ?? '',
  detailImageLabel: row.detail_image_label ?? '',
  ...(row.image_url ? { image: row.image_url } : {}),
  ...(row.image_alt ? { imageAlt: row.image_alt } : {}),
  ...(row.detail_image_url ? { detailImage: row.detail_image_url } : {}),
  ...(row.detail_image_alt ? { detailImageAlt: row.detail_image_alt } : {}),
}))
if (events) writeModule('cercle-events.ts', 'cercle_events', 'events', events)
